<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBewrzgc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBewrzgc/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBewrzgc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBewrzgc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBewrzgc\appProdProjectContainer([
    'container.build_hash' => 'Bewrzgc',
    'container.build_id' => '5ff1d4b9',
    'container.build_time' => 1604163940,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBewrzgc');
